In [19]:
import numpy as np
arr = np.arange(8)
arr


array([0, 1, 2, 3, 4, 5, 6, 7])

In [20]:
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
arr = np.arange(8)
arr_new =  arr.reshape((2 ,4))
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [22]:
arr = np.arange(8)
arr_new =  arr.reshape((2 ,4) , order = 'F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [23]:
arr = np.arange(8)
arr.shape = (2,4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [24]:
 arr_trans = arr.transpose()
 arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])